name: nx-base-current
on:
  push:
    paths:
      - "apps/nx-base/**"
      - ".github/workflows/**"
    branches:
      - 'current'

jobs:
  nx-base:
    if: github.repository == 'PRB-Services-LLC/sandbox-template'
    runs-on: ubuntu-latest
    steps:
      - name:  Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: clone repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: setup yarn
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      # - name: nx build
      #   if: github.event_name != 'pull_request'
      #   uses: mansagroup/nrwl-nx-action@v3
      #   with:
      #     targets: container
      #     projects: nx-base
      #     args: --configuration=current
      #     github-token: ${{secrets.GITHUB_TOKEN}}

      - name: nx build && push
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn nx container nx-base --configuration=current-branch

      - name: docker image list
        run: docker image list