name: nx-base-dev
on:
  push:
    paths:
      - "apps/nx-base/**"
    branches:
      - trunk
    tags:
      - 'v**-alpha.**'

jobs:
  output-github:
    if: github.repository == 'PRB-Services-LLC/sandbox-template'
    runs-on: ubuntu-latest
    steps:
      - name: echo github
        run: echo '${{ toJSON(github) }}'

  nx-base:
    if: github.repository == 'PRB-Services-LLC/sandbox-template'
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: clone repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: setup yarn
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      # - name: nx build lts && push
      #   run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn nx container nx-base --configuration=lts-dev

      - name: nx build current && push
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn nx container nx-base --configuration=current-trunk

      - name: docker image list
        run: docker image list
